[package]
name = "iso9660_simple"
version = "0.1.0"
edition = "2021"
authors = ["NDRAEY <pikachu_andrey@vk.com>"]
license = "MIT"
description = "ISO9660 structure and helper functions"
repository = "https://github.com/NDRAEY/iso9660_simple"


[dependencies]
