[package]
name = "iso9660_simple"
version = "0.1.7"
edition = "2021"
authors = ["NDRAEY <pikachu_andrey@vk.com>"]
license = "MIT"
description = "ISO9660 reading library (WIP)"
repository = "https://github.com/NDRAEY/iso9660_simple"

[features]
default = ["std"]
std = []

[dependencies]
